---
title: MSTEAMS.ME
author: Mitchell Bakker
email: mail@mitchellbakker.nl
description: Microsoft Teams Blog - Latest News
baseurl: "/ubuild-jekyll"
url: https://msteams.me
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
